#! /bin/sh

pulseaudio --start & 
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
feh --bg-scale $HOME/Pictures/pexels-nick-wehrli-3762284.jpg & 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Droidcam desktop='^7'
bspc rule -a 'Code - OSS' desktop='^3'

# Launch Polybar
$HOME/.config/polybar/launch.sh
