#! /bin/sh

pulseaudio --start & 
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
wal -i $HOME/Pictures/pexels-pixabay-46253.jpg &
feh --bg-scale "$(< "${HOME}/.cache/wal/wal")" & 

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Droidcam desktop='^7'
bspc rule -a 'Code - OSS' desktop='^3'

# Launch Polybar
$HOME/.config/polybar/launch.sh
